### ISSUE TITLE
GallTei urgent

### ISSUE THREAD

**Issue by glorieux-f** [OBVIL/Histoire-empirique-Obvil-Stanford#1]
- en-têtes TEI standard (et pas seulement &lt;dc:truc>machin&lt;/dc:truc>)
- conformité XML, cf fichiers attachés

[bpt6k58650679.txt](https://github.com/OBVIL/critique2000/files/747605/bpt6k58650679.txt)
[bpt6k122824w.txt](https://github.com/OBVIL/critique2000/files/747606/bpt6k122824w.txt)

**Comment by AlexandreGefen** [comment]
La validation est secondaire mais jette un coup d'œil sur les deux fichiers non conformes que je t'ai envoyée par email

**Comment by glorieux-f** [comment]
A priori, le seul problème concerne des & dans les champs de métadonnées. Le &lt;teiHeader> semble OK. Tu fermes le bug si tu es content.
